--  CREATE TABLE IF NOT EXISTS "users" ("_id"   SERIAL UNIQUE , "employeeNumber" INTEGER NOT NULL UNIQUE, "deleted" BOOLEAN NOT NULL DEFAULT false, "name" VARCHAR(255) NOT NULL, "password" VARCHAR(255) NOT NULL, "role" VARCHAR(255) NOT NULL, "createdBy" VARCHAR(255) NOT NULL, "createdAt" VARCHAR(255) NOT NULL, PRIMARY KEY ("_id"));

-- CREATE TABLE IF NOT EXISTS "tables" ("_id"   SERIAL UNIQUE , "number" INTEGER NOT NULL UNIQUE, "seats" INTEGER NOT NULL, "createdBy" VARCHAR(255) NOT NULL, "createdAt" VARCHAR(255) NOT NULL, PRIMARY KEY ("_id"));

--  CREATE TABLE IF NOT EXISTS "reservations" ("_id"   SERIAL UNIQUE , "customers" INTEGER NOT NULL, "from" DOUBLE PRECISION NOT NULL, "to" DOUBLE PRECISION NOT NULL, "createdBy" VARCHAR(255) NOT NULL, "createdAt" VARCHAR(255)
-- NOT NULL, "tableNumber" INTEGER REFERENCES "tables" ("number") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("_id"));